Feature/actualizar planes
udistrital/plan_adquisiciones_cliente pull request #109
Opened 2022-03-15 05:08 UTC by brayanpasa99

Actualizar Plan de Adquisiciones en API de configuración al publicar

2022-03-16 16:27 UTC, AlexFBP requested changes
En general, bien
No dejar constantes quemadas, o traerlas al menos del mismo lado...

2022-03-16 16:27 UTC, AlexFBP commented on src/app/utils/common/helpers/actualizar-publicado-configuracion.service.ts
> +  public creaPlanesdeAdquisicionActivos(id_general = '6182f3f72b95b39aff6a5430', id_idexud = '613ac16a2b95b39aff6a5429') {
Estos ID no son los que se traen/registran en configuracion_crud/api?
Por lo menos hacer que vengan de una constante, que podría estar declarada antes de `@Injectable(...`

2022-03-16 16:27 UTC, AlexFBP commented on src/app/utils/common/helpers/actualizar-publicado-configuracion.service.ts
> +                plan_adquisiciones_idexud: '613ac16a2b95b39aff6a5429',
De la mano con el comentario de la L15, traer estas constantes del mismo lado, de la misma variable / función

2022-03-17 22:04 UTC, brayanpasa99 commented on src/app/utils/common/helpers/actualizar-publicado-configuracion.service.ts
> +  public creaPlanesdeAdquisicionActivos(id_general = '6182f3f72b95b39aff6a5430', id_idexud = '613ac16a2b95b39aff6a5429') {
Se llaman los ID de constantes definidas para todo el controlador, ahora, esas constantes se dejan ahí dado que de momento permitirán acceder a la función con unos valores por defecto y eso será beneficioso en pruebas

2022-03-24 22:57 UTC, AlexFBP approved these changes

2022-03-24 23:06 UTC, AlexFBP commented
[Build OK](https://hubci.portaloas.udistrital.edu.co/udistrital/plan_adquisiciones_cliente/190)

2022-03-24 23:07 UTC, merged