release 1.0.0 -> master
udistrital/plan_adquisiciones_cliente pull request #116
Opened 2022-04-18 17:15 UTC by brayanpasa99

Resuelve: udistrital/financiera_documentacion#411

2022-04-22 15:49 UTC, AlexFBP commented
Tuleap
- [Despliegue](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=46782)
- [Pruebas de Carga y Seguridad](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=46779)

2022-04-25 06:39 UTC, AlexFBP requested changes
- Comentarios principales en los archivos:
  - `src/app/pages/admin-conf/planes-adq-activos/planes-adq-activos.component.html`
  - `src/app/pages/admin-conf/planes-adq-activos/planes-adq-activos.component.ts`
  - `src/app/pages/admin-conf/planes-adq-activos/planes-adq-activos.component.html`
  - `src/app/pages/primer-modulo/componentes/componente-prueba/componente-prueba.component.html`
  - `src/app/pages/registro-plan-adquisiciones/components/form-productos-asociados/form-productos-asociados.component.ts`
  - `src/app/pages/registro-plan-adquisiciones/components/tabla-actividades-fuentes/tabla-actividades-fuentes.component.ts`
- El resto (la mayoría de los demas comentarios) y en general; hacer que cualquier texto destinado a interfaz, pase por i18n/translate. Si se pueden reaprovechar textos ya existentes, mejor
- Algunos codigos comentados a eliminar o comentar
- Algunos archivos no terminan con una línea vacía

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/tabla-actividades-fuentes/tabla-actividades-fuentes.component.ts
> +        if (accion.accion.title === 'Editar Actividad y Fuentes Asociadas') {
REVISAR: Esto está dependiendo de la visualización, debería depender de la lógica... ¿De qué depende que `title === 'Editar Actividad y Fuentes Asociadas'`? Ese criterio debería ser del que dependa esta lógica

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/tabla-actividades-fuentes/tabla-actividades-fuentes.component.ts
> +    this.popupService.showInfoAlert('Selecciona el centro gestor, el area funcional, y al menos una meta', 'Info');
Traer de i18n

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/ver-actividades/ver-actividades.component.html
> +</div>
(En general) Dejar vacía la última línea de cualquier archivo de texto plano
```suggestion
</div>

```

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/ver-actividades/ver-actividades.component.html
> +</div>
Revisar si esto se puede reducir como
```suggestion
<ngx-general-table class="container row col px-0"
*ngIf="DatosTransformados" [config]="configuracion" [datos]="DatosTransformados"></ngx-general-table>
```

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/interfaces/interfaces.ts
> +        name: 'Codificacion UNSPSC',
(En general para este archivo) Revisar si los `name` y otros campos destinados a la interfaz, se puedan colocar directamente claves i18n, o usar `translate.instant()` para ello... Traer de i18n, mejor dicho

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/registro-plan-adquisiciones.module.ts
> +// import { SeleccionMetaProductoComponent } from './components/seleccion-meta-producto/seleccion-meta-producto.component';
```suggestion
```

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/registro-plan-adquisiciones.module.ts
> +// import { ActividadFuncionamientoComponent } from './components/actividad-funcionamiento/actividad-funcionamiento.component';
```suggestion
```

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/welcome/components/init/init.component.html
> +    alt="Logo Kronos Universidad Distrital Francisco José de Caldas"
Traer de i18n

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/welcome/components/init/init.component.ts
> +  }
Mirar si se puede eliminar una o ambas funciones. No olvidar quitar el `implements OnInit` de esta `class` para ello

2022-04-25 06:39 UTC, AlexFBP commented on src/app/shared/components/datos-generales-iniciales/datos-generales-iniciales.component.html
> +                                    <label for="exampleFormControlSelect2">Área Funcional:</label>
Traer de i18n

2022-04-25 06:39 UTC, AlexFBP commented on src/app/shared/components/general-table/general-table.component.html
> +          placeholder="Campo de Búsqueda" [(ngModel)]="stringBusqueda">
Traer placeholder de i18n

2022-04-25 06:39 UTC, AlexFBP commented on src/app/shared/components/tabla-plan-adquisiciones/tabla-plan-adquisiciones.component.html
> +                            Total {{datos.FuenteData.Nombre}}:
- Traer de i18n
- Usar interpolacion

2022-04-25 06:39 UTC, AlexFBP commented on src/app/shared/components/tabla-plan-adquisiciones/tabla-plan-adquisiciones.component.html
> +</div>
```suggestion
</div>

```

2022-04-25 06:39 UTC, AlexFBP commented on src/app/shared/components/tabla-rubros-plan/tabla-rubros-plan.component.html
> +    Total {{datos.RubroInfo.Nombre}}:
- Traer de i18n
- Usar interpolación

2022-04-25 06:39 UTC, AlexFBP commented on src/app/shared/components/tabla-rubros-plan/tabla-rubros-plan.component.html
> +</th>
```suggestion
</th>

```

2022-04-25 06:39 UTC, AlexFBP commented on src/app/shared/components/tabla-rubros-plan/tabla-rubros-plan.component.ts
> +/* tslint:disable:component-selector */
Revisar si es que aparece algún error al correr `npm run lint` asociado a este archivo, al eliminar esta línea:
```suggestion
```

2022-04-25 06:39 UTC, AlexFBP commented on src/app/shared/services/shared.service.ts
>      // const unidadEjecutora = 1;
Eliminar, Revisar y/o ajustar estos comentarios
```suggestion
```

2022-04-25 06:39 UTC, AlexFBP commented on src/app/utils/common/helpers/actualizar-publicado-configuracion.service.ts
> +const IDPLANIDEXUD = '613ac16a2b95b39aff6a5429';
De la mano con lo comentado a `src/app/pages/admin-conf/planes-adq-activos/planes-adq-activos.component.ts`, revisar si estos ID "quemados" siguen siendo necesarios. De ser así, traerlos de los `src/environment/*.ts`

2022-04-25 06:39 UTC, AlexFBP commented on src/app/utils/common/helpers/actualizar-publicado-configuracion.service.ts
> +          // FIXME: Hacer el Put
Revisar si este `FIXME` sigue aplicando
```suggestion
```

2022-04-25 06:39 UTC, AlexFBP commented on src/app/utils/common/helpers/actualizar-publicado-configuracion.service.ts
> +          });
Si no se está haciendo nada, eliminar esta parte
```suggestion
```

2022-04-25 06:39 UTC, AlexFBP commented on src/app/utils/common/helpers/actualizar-publicado-configuracion.service.ts
> +              });
Si no se hace nada, eliminar esto...
```suggestion
```

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/planes/components/detalle-version-plan/detalle-version-plan.component.ts
>          if (accion.accion.name === 'Ver') {
REVISAR: A no ser que el `name` no se vaya a usar directamente en la interfaz, esta lógica estaría dependiendo de un texto de interfaz... Debería depender de lo que sea que haga que `name === 'Ver'`

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/planes/components/detalle-version-plan/detalle-version-plan.component.ts
> +        title: 'Ver Version',
Traer de i18n

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/planes/components/detalle-version-plan/detalle-version-plan.component.ts
>          name: 'Ver',
Traer de i18n

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/planes/components/detalle-version-plan/detalle-version-plan.component.ts
> +    // this.subscription4$.unsubscribe();
Eliminar
```suggestion
```
O agregar también la razón del comentario

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/planes/components/detalle-version-plan/detalle-version-plan.component.ts
> +          text: `PLAN DE ADQUISICIONES DE BIENES Y SERVICIOS DE LA UNIVERSIDAD DISTRITAL VIGENCIA ${this.PlanAdquisiciones.Vigencia}`,
Traer de i18n

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/planes/components/detalle-version-plan/detalle-version-plan.component.ts
> +          text: this.ordinalPipe.transform(this.index) +
Traer de i18n, usar interpolación

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/planes/components/detalle-version-plan/detalle-version-plan.component.ts
> +          text: 'Total Rubro ' + Rubro.Nombre,
Traer de i18n, usar interpolación

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/planes/components/detalle-version-plan/detalle-version-plan.component.ts
> +          text: 'TOTAL PLAN ' + Fuente.Nombre,
- Traer de i18n
- Usar interpolación
- Para la mayúscula, usar [`toUpperCase()`](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase) - Alternativamente, si ya hay una clase global que tenga `text-transform: uppercase`, intentar colocarsela a `style: `

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/planes/components/detalle-version-plan/detalle-version-plan.component.ts
> +          text: `PLAN DE ADQUISICIONES DE BIENES Y SERVICIOS DE LA UNIVERSIDAD DISTRITAL VIGENCIA ${this.PlanAdquisiciones.Vigencia}`,
- Traer de i18n
- Usar interpolación
- Usar [`toUpperCase()`](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase) en el string resultante - Alternativamente, si ya hay una clase global que tenga `text-transform: uppercase`, intentar colocarsela a `style: `

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss
> +.overflow {
Estilos repetidos, mover a un componente más general...

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/form-productos-asociados/form-productos-asociados.component.scss
> +}
Estilos repetidos en `src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss` (ver comentario dejado allá)

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/metas-asociadas/metas-asociadas.component.ts
> +          if (accion.accion.title === 'Asociar Nueva Meta') {
REVISAR: Lógica estaría dependiendo de un texto de interfaz, que a su vez debería venir de i18n. Debería depender de lo que haga que `title = 'Asociar Nueva Meta'`

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/metas-asociadas/metas-asociadas.component.ts
> +          if (accion.accion.title === 'Eliminar Meta Asociada') {
REVISAR: Lógica estaría dependiendo de un texto de interfaz, que a su vez debería venir de i18n. Debería depender de lo que haga que `title = 'Eliminar Meta Asociada'`

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/modalidades-seleccion/modalidades-seleccion.component.scss
> +}
Estilos repetidos en `src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss` (ver comentario dejado allá)

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/seleccion-datos-generales/seleccion-datos-generales.component.scss
> +}
Estilos repetidos en `src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss` (ver comentario dejado allá)

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/seleccion-fuente/seleccion-fuente.component.scss
> +}
Estilos repetidos en `src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss` (ver comentario dejado allá)

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/seleccion-rubro/seleccion-rubro.component.scss
> +}
Estilos repetidos en `src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss` (ver comentario dejado allá)

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/tabla-codificacion-arka/tabla-codificacion-arka.component.scss
> +}
Estilos repetidos en `src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss` (ver comentario dejado allá)

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/lineamientos/components/table-lineamientos/table-lineamientos.component.scss
> +}
Estilo repetido en `src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss` (ver comentario dejado allá)

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/metas/components/table-metas/table-metas.component.scss
> +}
Estilo repetido en `src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss` (ver comentario dejado allá)

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/form-actividad-fuentes/form-actividad-fuentes.component.scss
> +}
Estilos (casi) repetidos en `src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss` (ver comentario dejado allá)

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/form-codificacion-arka/form-codificacion-arka.component.scss
> +}
Estilos (casi) repetidos en `src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss` (ver comentario dejado allá)

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/form-ficha-tecnica/form-ficha-tecnica.component.scss
> +}
Estilos repetidos en `src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss` (ver comentario dejado allá)

2022-04-25 06:39 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/form-fuentes-financiamiento/form-fuentes-financiamiento.component.scss
> +}
Estilos repetidos en `src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.scss` (ver comentario dejado allá)

2022-04-26 16:30 UTC, AlexFBP commented
Se aplica el merge para poder preparar el ambiente de producción. Los comentarios dejados en este PR se resolverán bajo este PR (#116) y el Issue #118

2022-04-26 16:30 UTC, merged

2022-05-02 13:45 UTC, brayanpasa99 commented on src/app/pages/admin-conf/planes-adq-activos/planes-adq-activos.component.html
> +<h1>Works</h1>
Porque se hizo un componente pensado para cambiar el plan de adquisiciones, sin embargo, por diferentes circunstancias se decidió posponer la tarea hasta el punto de usar el último plan de adquisiciones publicado. Se deja el componente vacío

Se deja la propiedad `template: ''` dado que se presentan problemas al quitar la propiedad.

2022-05-02 13:55 UTC, brayanpasa99 commented on src/app/pages/admin-conf/planes-adq-activos/planes-adq-activos.component.ts
> +  private creaPlanesdeAdquisicionActivos(id_general = '6182f3f72b95b39aff6a5430', id_idexud = '613ac16a2b95b39aff6a5429') {
En caso de necesitar hacer un cambio en los id guardados podría servir, se dejan en el archivo `environment.ts`

2022-05-02 13:55 UTC, brayanpasa99 commented on src/app/pages/admin-conf/planes-adq-activos/planes-adq-activos.component.ts
> +          // FIXME: Hacer el Put
Resuelto, se elimina el comentario

2022-05-02 14:40 UTC, brayanpasa99 commented on src/app/pages/detalle-version-plan-adquisiciones/components/detalle-ficha-tecnica/detalle-ficha-tecnica.component.html
> +</div>
Se hace la prueba de quitar el HTML, sin embargo no se muestra la tabla de metas así que se condiera necesario y se deja igual.

2022-05-02 14:41 UTC, brayanpasa99 commented on src/app/pages/detalle-version-plan-adquisiciones/components/detalle-metas-asociadas/detalle-metas-asociadas.component.html
> +  </div>
Se hace la prueba de quitar el HTML, sin embargo no se muestra la tabla de metas así que se condiera necesario y se deja igual.

2022-05-02 14:42 UTC, brayanpasa99 commented on src/app/pages/detalle-version-plan-adquisiciones/components/detalle-ficha-tecnica/detalle-ficha-tecnica.component.html
> +</div>
Se considera necesario el código resaltado, se deja igual.

2022-05-02 14:43 UTC, brayanpasa99 commented on src/app/pages/detalle-version-plan-adquisiciones/components/detalle-productos-asociadas/detalle-productos-asociadas.component.html
> +  </div>
Se considera necesario el código resaltado, se deja igual.

2022-05-02 17:58 UTC, brayanpasa99 commented on src/app/pages/detalle-version-plan-adquisiciones/components/layout/layout.component.html
> +                                            <!-- <button class="btn btn-primary text-light" matStepperNext>Siguiente</button> -->
Eliminado

2022-05-02 17:58 UTC, brayanpasa99 commented on src/app/pages/detalle-version-plan-adquisiciones/components/layout/layout.component.html
> +                                    </mat-step> -->
Eliminado

2022-05-02 18:21 UTC, brayanpasa99 commented on src/app/pages/metas/components/layout/layout.component.html
>      </div>
Se consideran necesarias las líneas de código.

2022-05-02 18:35 UTC, brayanpasa99 commented on src/app/pages/metas/components/layout/layout.component.ts
>    }
Se elimina y se modifican los implements e importaciones.

2022-05-02 18:40 UTC, brayanpasa99 commented on src/app/pages/metas/components/table-metas/table-metas.component.ts
> +  // }
Eliminado

2022-05-02 18:41 UTC, brayanpasa99 commented on src/app/pages/metas/effects/metas.effects.ts
> +      // this.store.select(getLineamientoSeleccionado),
Eliminado

2022-05-02 18:41 UTC, brayanpasa99 commented on src/app/pages/metas/effects/metas.effects.ts
> +      // }
Eliminado

2022-05-03 16:06 UTC, brayanpasa99 commented on src/app/pages/planes/components/detalle-plan/detalle-plan.component.html
> +            TOTAL PLAN DE FUNCIONAMIENTO E INVERSIÓN VIGENCIA 2021: <!--!TODO: Cambiar la vigencia por una no quemada-->
Se usa el pipe de uppercase de Angular para las mayusculas, además de eso el TODO está por solucionar y se tratará al cerrar udistrital/plan_adquisiciones_cliente#117

2022-05-03 17:00 UTC, brayanpasa99 commented on src/app/pages/primer-modulo/componentes/componente-prueba/componente-prueba.component.html
>          </div>
Aparentemente es un componente de pruebas porque no se observa comportamiento al descomentar las líneas. Se deja template vacío

2022-05-03 17:06 UTC, brayanpasa99 commented on src/app/pages/primer-modulo/componentes/componente-prueba/componente-prueba.component.ts
> +  }
Se resuelve eliminar el módulo ya que queda vacío y en caso de necesitarse hacer pruebas se creará uno temporal nuevamente

2022-05-04 17:55 UTC, brayanpasa99 commented on src/app/pages/registro-plan-adquisiciones/components/form-productos-asociados/form-productos-asociados.component.ts
> +          if (fila.accion.title === 'Editar Producto Asociado') {
Al parecer el `title` al que se hace referencia es al que proviene de la acción desplegada por el uso de ngRX Store y no el que se trae de i18n. Se espera revisar al finalizar udistrital/plan_adquisiciones_cliente#117. Por otro lado, ¿Afecta la funcionalidad?

2022-05-04 18:26 UTC, brayanpasa99 commented on src/app/pages/registro-plan-adquisiciones/components/layout/layout.component.ts
>      this.titulo = 'Creacion Plan de Adquisiciones';
Hay problemas con hacer la traducción directamente en el HTML dado que es un atributo Input de otro componente, solamente se hace el cambio para traer de i18n

2022-05-04 18:47 UTC, brayanpasa99 commented on src/app/pages/registro-plan-adquisiciones/components/layout/layout.component.ts
> +        // });
Se elimina dado que en lo que se ha trabajado del cliente no se observa una influencia negativa del segmento de código

2022-05-05 18:26 UTC, brayanpasa99 commented on src/app/shared/components/tabla-rubros-plan/tabla-rubros-plan.component.ts
> +/* tslint:disable:component-selector */
Se verifica nuevamente el problema dado que se presentan fallas al corregir los errores al ejecutar `npm run prepush`

Se obtiene el siguiente error:

![ErrorPrepush](https://user-images.githubusercontent.com/42362278/166989135-cbfe1da0-a3f8-4c06-a92f-cb299522ec32.png)

El cliente deja de funcionar, se deja la línea comentada y que se había eliminado antes