Feature/PDF y datos repetidos
udistrital/plan_adquisiciones_cliente pull request #123
Opened 2022-04-29 02:43 UTC by brayanpasa99

Resuelve: udistrital/plan_adquisiciones_cliente#117

2022-04-29 06:04 UTC, AlexFBP commented on src/app/pages/planes/services/planes.service.ts
> +      'Meta: ' + element.NumeroMeta + ' - Actividad: ' + element.Numero + '. ' + element.Nombre
(En general) Para textos de interfaz, traer de i18n, usar interpolación para inyectar los datos en el string
- Documentación: https://github.com/ngx-translate/core#3-init-the-translateservice-for-your-application
- Ejemplo 1:
  - .ts: https://github.com/udistrital/arka_cliente/blob/0252f60779d29446f039a8d2736dfe22b80b7c99/src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts#L634
  - .json: https://github.com/udistrital/arka_cliente/blob/0252f60779d29446f039a8d2736dfe22b80b7c99/src/assets/i18n/es.json#L422
- Ejemplo 2:
  - .html: https://github.com/udistrital/arka_cliente/blob/0252f60779d29446f039a8d2736dfe22b80b7c99/src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.html#L168
  - .json: https://github.com/udistrital/arka_cliente/blob/0252f60779d29446f039a8d2736dfe22b80b7c99/src/assets/i18n/es.json#L420

2022-04-29 06:06 UTC, AlexFBP commented on src/app/pages/planes/components/detalle-version-plan/detalle-version-plan.component.ts
> +              text: 'No Aplica',
Traer texto mediante i18n

2022-04-29 06:06 UTC, AlexFBP commented on src/app/pages/planes/components/detalle-plan/detalle-plan.component.html
> +            TOTAL PLAN DE FUNCIONAMIENTO E INVERSIÓN VIGENCIA 2022: <!--!TODO: Cambiar la vigencia por una no quemada-->
1. Traer de i18n, usar interpolación (ver lo comentado en `src/app/pages/planes/services/planes.service.ts`)
2. Definir de una vez la variable que desde el .ts traería la vigencia
3. Si se ha de dejar quemado el 2022, que sea al menos en el valor de inicialización en el constructor del .ts respectivo. Si se puede ajustar de una vez a que la vigencia actual venga, bien sea de un parametro en la inicialización del cliente o, mejor aún, del store (NgRx ?) (Se podría mencionar en el/los commit el Issue de parametrizacion de vigencias)

2022-05-05 19:41 UTC, brayanpasa99 commented on src/app/pages/planes/services/planes.service.ts
> +    return [fuentesNoRepeated, actividades];
Se deja el filter con el fin de obtener los atributos no repetidos basándose en su posición en el arreglo y el elemento considerado. Especificar si es necesario cambiar a map

2022-05-05 19:57 UTC, AlexFBP requested changes
En general, bien. Algunas cositas a revisar...

2022-05-05 19:57 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/layout/layout.component.ts
> +    this.titulo = this.translate.instant('PLAN_ADQUISICIONES.creacion_plan');
Revisar: En caso que el `titulo` no cambie, mirar si se puede evitar esta variable, y traer directamente desde el html de manera similar a la L4 de `src/app/pages/welcome/components/init/init.component.html`

2022-05-05 19:57 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/form-productos-asociados/form-productos-asociados.component.ts
> +    this.boton = this.translate.instant('GLOBAL.asociar');
Revisar: En caso que el `titulo` o el `boton` cambie, mirar si se puede(n) evitar esta(s) variable(s), y traer directamente desde el html de manera similar a la L4 de `src/app/pages/welcome/components/init/init.component.html` (aplicar según sea el caso)

2022-05-05 19:57 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/form-metas-asociadas/form-metas-asociadas.component.ts
> +    this.boton = this.translate.instant('GLOBAL.asociar');
1. Revisar: En caso que el `titulo` o el `boton` cambie, mirar si se puede(n) evitar esta(s) variable(s), y traer directamente desde el html de manera similar a la L4 de `src/app/pages/welcome/components/init/init.component.html` (aplicar según sea el caso)
2. No concatenar traducciones, usar una única con interpolación y/o crear una nueva llave i18n

2022-05-05 19:57 UTC, AlexFBP commented on src/app/pages/planes/components/detalle-plan/detalle-plan.component.html
>  </div>
```suggestion
</div>

```

2022-05-05 19:57 UTC, AlexFBP commented on src/app/utils/common/helpers/actualizar-publicado-configuracion.service.ts
> +const IDPLANIDEXUD = environment.IDPLANADQUISICIONESIDEXUD;
- Revisar: Aparentemente, o por lo menos en esta rama, esta variable no se encuentra declarada, fallaría esta parte al compilar? (Revisar los environment*.ts)
- Revisar: Por otro lado, si entiendo bien, los valores adecuados, los id no deberían traerse-de/publicarse-a un registro en configuracion_crud.parametro?

2022-05-16 18:00 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/productos-asociados/productos-asociados.component.ts
> +    private translateHelper: TranslateFormItemsHelper
```suggestion
    private translateHelper: TranslateFormItemsHelper,
```

2022-05-16 18:01 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/productos-asociados/productos-asociados.component.ts
> +    this.configuracion = this.translateHelper.translateItemTableConfiguration(this.configuracion);
```suggestion
    this.configuracion = this.translateHelper
      .translateItemTableConfiguration(CONFIGURACION_TABLA_PRODUCTOS_ASOCIADOS);
```

2022-05-16 18:02 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/tabla-actividades-fuentes/tabla-actividades-fuentes.component.ts
> +    private translateHelper: TranslateFormItemsHelper
```suggestion
    private translateHelper: TranslateFormItemsHelper,
```

2022-05-16 18:03 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/tabla-codificacion-arka/tabla-codificacion-arka.component.ts
> +    private translateHelper: TranslateFormItemsHelper
```suggestion
    private translateHelper: TranslateFormItemsHelper,
```

2022-05-16 18:03 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/tabla-codificacion-arka/tabla-codificacion-arka.component.ts
> +    this.configuracion = this.translateHelper.translateItemTableConfiguration(this.configuracion);
```suggestion
    this.configuracion = this.translateHelper
      .translateItemTableConfiguration(CONFIGURACION_TABLA_ELEMENTOS_ARKA);
```

2022-05-16 18:05 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/tabla-ficha-tecnica/tabla-ficha-tecnica.component.ts
> +    this.configuracion = this.translateHelper.translateItemTableConfiguration(this.configuracion);
```suggestion
    this.configuracion = this.translateHelper
      .translateItemTableConfiguration(CONFIGURACION_TABLA_FICHA_ESTADISTICA);
```

2022-05-16 18:05 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/ver-actividades/ver-actividades.component.ts
> +  constructor(private translateHelper: TranslateFormItemsHelper) {
```suggestion
  constructor(
    private translateHelper: TranslateFormItemsHelper,
  ) {
```

2022-05-16 18:06 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/ver-actividades/ver-actividades.component.ts
> +    this.configuracion = this.translateHelper.translateItemTableConfiguration(this.configuracion);
```suggestion
    this.configuracion = this.translateHelper
      .translateItemTableConfiguration(CONFIGURACION_TABLA_VER_ACTIVIDADES);
```

2022-05-16 18:10 UTC, AlexFBP commented on src/environments/environment.ts
> +  // PLAN_CUENTAS_MID_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8204/v1/',
Revisar:
- Algunos con localhost
- Eliminar los comentados

Ajustar en los otros environment* de ser necesario

2022-05-17 02:54 UTC, brayanpasa99 commented on src/app/pages/planes/interfaces/interfaces.ts
> +  },
Se cambió porque la información del PDF no es coherente con el orden anterior. Teniendo en cuenta eso, se generó el PDF y no hubo implicaciones negativas.

2022-05-17 02:54 UTC, brayanpasa99 commented on src/environments/environment.ts
> +  // PLAN_CUENTAS_MID_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8204/v1/',
Se comentan los de localhost, la pregunta es si se puede dejar el de desarrollo con comentarios dado que es más fácil para montar en local, el de producción no tiene comentarios.

2022-05-18 05:58 UTC, AlexFBP requested changes
Un único comentario a revisar y quedaría

2022-05-18 05:58 UTC, AlexFBP commented on src/assets/i18n/es.json
> +    "": "Editar Actividad"
REVISAR: Quizás faltó esto...? (Revisar antes de aplicar este _suggested change_)
```suggestion
    "editar_actividad": "Editar Actividad"
```

2022-05-19 22:05 UTC, AlexFBP commented on src/app/pages/detalle-version-plan-adquisiciones/components/detalle-ficha-tecnica/detalle-ficha-tecnica.component.ts
>      this.Datos = [];
Cierto, dejemolo así

2022-05-19 22:05 UTC, AlexFBP commented on src/environments/environment.ts
> +  // PLAN_CUENTAS_MID_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8204/v1/',
Vale, dejemolo así

2022-05-19 22:05 UTC, AlexFBP approved these changes

2022-05-19 22:08 UTC, AlexFBP commented
[Falló el Build...](https://hubci.portaloas.udistrital.edu.co/udistrital/plan_adquisiciones_cliente/224/1/8)
![image](https://user-images.githubusercontent.com/6588872/169412609-756d32f0-23f2-4420-9937-2893eb0a1ac7.png)

2022-05-21 02:12 UTC, AlexFBP requested changes

2022-05-21 02:12 UTC, AlexFBP commented on src/environments/shared.ts
> +  CLIENTE_PRESUPUESTO: '/pages/plan-cuentas',
```suggestion
  CLIENTE_PRESUPUESTO: 'https://pruebaspresupuesto.portaloas.udistrital.edu.co/pages',
```

2022-05-21 02:12 UTC, AlexFBP commented on src/environments/environment.prod.ts
>    production: true,
```suggestion
  CLIENTE_PRESUPUESTO: 'https://presupuesto.portaloas.udistrital.edu.co/',
  CLIENTE_CONTABILIDAD: 'https://contabilidad.portaloas.udistrital.edu.co/',
  production: true,
```

De paso, abajo en el `TOKEN`, actualizar las siguientes propiedades:
```typescript
{
REDIRECT_URL: 'https://planadquisiciones.portaloas.udistrital.edu.co/',
SIGN_OUT_REDIRECT_URL: 'https://planadquisiciones.portaloas.udistrital.edu.co/',
}
```

2022-05-21 02:12 UTC, AlexFBP commented on src/environments/environment.ts
> +  // ADMINISTRATIVA_PRUEBAS_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8104/v1/',
```suggestion
```

2022-05-21 02:12 UTC, AlexFBP commented on src/environments/environment.ts
> +  // PLAN_CUENTAS_MID_SERVICE: 'http://pruebasapi.intranetoas.udistrital.edu.co:8204/v1/',
```suggestion
```

2022-05-24 02:03 UTC, AlexFBP approved these changes

2022-05-24 02:03 UTC, AlexFBP commented
[Build OK](https://hubci.portaloas.udistrital.edu.co/udistrital/plan_adquisiciones_cliente/229)

2022-05-24 02:03 UTC, merged