Feature/actualizacion rubros
udistrital/plan_adquisiciones_cliente pull request #96
Opened 2021-12-31 03:10 UTC by brayanpasa99

2022-01-01 01:40 UTC, AlexFBP reviewed
De momento va bien, un solo comentario respecto a dependencias

2022-01-01 01:40 UTC, AlexFBP commented on package.json
> +    "@ngrx/store-devtools": "^8.6.0",
Averiguar si esta dependencia se puede instalar como una dependencia de desarrollo. En caso afirmativo, ejecutar...
```bash
npm i -D @ngrx/store-devtools@^8.6.0
```
... para ajustar los package*.json

2022-01-06 16:21 UTC, brayanpasa99 commented on package.json
> +    "@ngrx/store-devtools": "^8.6.0",
No encuentro mucha información, se hace el comando pero envía error, se deja como está

2022-01-06 21:18 UTC, AlexFBP requested changes

2022-01-06 21:18 UTC, AlexFBP commented on src/app/pages/registro-plan-adquisiciones/components/layout/layout.component.ts
> +        // });
Eliminar
```suggestion
```
Alternativamente, dejar comentado (en código) por qué se dejó comentado y/o cómo proceder

2022-01-07 02:59 UTC, AlexFBP approved these changes

2022-01-07 03:46 UTC, AlexFBP approved these changes

2022-01-07 03:47 UTC, AlexFBP commented
[Build OK](https://hubci.portaloas.udistrital.edu.co/udistrital/plan_adquisiciones_cliente/165)

2022-01-07 03:47 UTC, merged